[workspace]
members = [
    "jigsaw",
    "core",
    "bench",
]

# Use optimisations even on debug builds - compilation is fast and the unoptimised code is
# SLLLLOOOOOOOW
[profile.dev]
opt-level = 3
