[package]
name = "proj"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.45"
proj_core = { path = "../core" }
serde = "1.0.117"
serde_json = "1.0.59"
itertools = "0.10.0"

[lib]
crate-type = ["cdylib"]
