name: Build

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install wasm-bindgen
      uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        version: 'latest'

    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown

    - uses: actions/checkout@v2
      with:
        # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        persist-credentials: false
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    # Cache rust's build files to speed up the CI runs
    - uses: Swatinem/rust-cache@v1

    - name: Checkout site
      run: |
        # Clone my site's git repo into /tmp/site
        mkdir -p /tmp/site
        git clone https://github.com/kneasle/kneasle.github.io.git /tmp/site
        git config --global credential.helper store
        echo "kneasle:${{ secrets.SITE_TOKEN }}@github.com" >> ~/.git-credentials
        # Checkout the jigsaw branch
        cd /tmp/site
        git checkout jigsaw
        git status
        # Make sure this is up-to-date with the remote branch
        git pull
        # Move back to the Jigsaw repo
        cd -

    - name: Build project
      run: |
        mkdir -p /tmp/site/firehose
        ./build.py --release --out-dir /tmp/site/firehose

    - name: Commit changes
      run: |
        cd /tmp/site
        # Commit these new files
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add firehose
        # If no changes have occurred since the last build, then `git commit` will fail and cause
        # the entire run to fail.  This is not what we want - nothing will break if no new commits
        # are made, so instead we use the `||` to echo an error message and stop the overall command
        # from failing
        git commit -m "Update firehose branch" || echo "No changes to commit!"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SITE_TOKEN }}
        branch: 'jigsaw'
        directory: '/tmp/site'
        repository: kneasle/kneasle.github.io
